apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: linkding-connection-string
      remoteRef:
        key: linkding-connection-string
    - secretKey: linkding-storage-account-name
      remoteRef:
        key: linkding-storage-account-name
    - secretKey: linkding-blob-sas
      remoteRef:
        key: linkding-blob-sas
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db-creds
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: linkding-db-username
    - secretKey: password
      remoteRef:
        key: linkding-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-container-env
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding-superuser-name
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding-superuser-password
    - secretKey: LD_DB_USER
      remoteRef:
        key: linkding-db-username
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: linkding-db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: tunnel-credentials
      remoteRef:
        key: linkding-cloudflare-tunnel
