# NOTE: These must be set manually to the control plane IP addresses
# kubeEtcd:
#  endpoints:
#    - x.y.z.a
#    - x.y.z.b
#    - x.y.z.c
kubeControllerManager:
  service:
    selector:
      k8s-app: kube-controller-manager
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring

    # Discover all PodMonitors, Probes, PrometheusRules and ServiceMonitors
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  grafana.ini:
    # auth:
    #   disable_login_form: true
    #   disable_signout_menu: true
    # auth.basic:
    #   enabled: false
    # auth.anonymous:
    #   enabled: true
    date_formats:
      default_week_start: monday

  envFromSecret: grafana-env

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: health
          type: postgres
          url: health-db.mischavandenburg.net:5432
          user: health
          secureJsonData:
            password: $HEALTH_DB_PASSWORD
          jsonData:
            database: health
            sslmode: disable
            maxOpenConns: 100
            maxIdleConns: 100
            maxLifetime: 14400
            minIdleTimeoutMinutes: 1
            connMaxLifetime: 14400
            postgresVersion: 1500
            timescaledb: false
          version: 1
          editable: true

      deleteDatasources:
        - name: health
          orgId: 1

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 4Gi

  # Allow Omni Workload Proxying for this service
  service:
    annotations:
      omni-kube-service-exposer.sidero.dev/port: "50082"
      omni-kube-service-exposer.sidero.dev/label: Grafana
