apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelly-api
  template:
    metadata:
      labels:
        app: shelly-api
        policy-type: "app"
    spec:
      containers:
        - name: shelly-api
          image: ghcr.io/mischavandenburg/shelly:v0.1.2
          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: shelly-configmap
            - secretRef:
                name: shelly-container-env

      restartPolicy: Always
